// swift-tools-version: 5.6

// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import PackageDescription

let package = Package(
    name: "HorizonKeys",
    platforms: [
        .macOS(.v11),
        .iOS(.v11),
        .tvOS(.v11),
        .watchOS(.v4),
    ],
    products: [
        .library(
            name: "HorizonKeys",
            targets: ["HorizonKeys"]
        ),
    ],
    dependencies: [
        .package(name: "HorizonKeysInterfaces", path: "../HorizonKeysInterfaces"),
    ],
    targets: [
        .target(
            name: "HorizonKeys",
            dependencies: ["HorizonKeysInterfaces"],
            path: "Sources"
        ),
        .testTarget(
            name: "HorizonKeysTests",
            dependencies: ["HorizonKeys"],
            path: "Tests"
        ),
    ]
)
