// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol HorizonKeysGlobalProtocol {
}

public protocol HorizonKeysEnvironmentProtocol {
    var privateKey: String { get }
    var publicKey: String { get }
}
